server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:postgresql://orders-db-service:5432/orders-db
    username: postgres
    password: postgres
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/