server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders-db
    username: postgres
    password: postgres
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka