server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://products-db-service:5433/products-db
    username: postgres
    password: postgres
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-server-service:8761/eureka