server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products-db
    username: postgres
    password: postgres
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka