apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-orders-deployment
  labels:
    app: ms-orders-deployment
spec:
  selector:
    matchLabels:
      app: ms-orders-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-orders-deployment
    spec:
      containers:
        - name: ms-orders
          image: polloh/ms-orders
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "8090"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ORDERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ORDERS
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ORDERS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ORDERS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ORDERS
---
apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
  labels:
    app: ms-orders-service
spec:
  selector:
    app: ms-orders-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer