apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_ORDERS: cG9zdGdyZXM=
  DB_PASSWORD_ORDERS: cG9zdGdyZXM=
  DB_USER_PRODUCTS: cG9zdGdyZXM=
  DB_PASSWORD_PRODUCTS: cG9zdGdyZXM=