server:
  port: 8084
spring:
  application:
    name: ms-config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/hector-gallardo-araya/ayudantia-microservicios
          search-paths: config-data
